language: python
services: memcached
sudo: false

matrix:
  include:
  - python: "3.7"
    env: TOX_ENV=py37-django22
  - python: "3.7"
    env: TOX_ENV=py37-django30
  - python: "3.7"
    env: TOX_ENV=py37-django31
  - python: "3.8"
    env: TOX_ENV=py38-django30
  - python: "3.8"
    env: TOX_ENV=py38-django31
  - python: "3.8"
    env: TOX_ENV=py38-django32



install:
  - pip install tox

script:
  - tox -e $TOX_ENV
