language: python
services: memcached
sudo: false

matrix:
  include:
  - python: "3.6"
    env: TOX_ENV=py36-django22
  - python: "3.6"
    env: TOX_ENV=py36-django30
  - python: "3.6"
    env: TOX_ENV=py36-django31
  - python: "3.7"
    env: TOX_ENV=py37-django22
  - python: "3.7"
    env: TOX_ENV=py37-django30
  - python: "3.7"
    env: TOX_ENV=py37-django31



install:
  - pip install tox

script:
  - tox -e $TOX_ENV
